- name: ABE_BOOKS_CLIENT_KEY
  type: text
  required: true
- name: REDIRECT_LINKS_KEY
  type: text
  required: true
- name: ABE_BOOKS_AFFILIATE_CODE
  type: text
  required: true
- name: BOL_CLIENT_KEY
  type: text
  required: true
